services:
  postgres:
    image: postgres:15
    container_name: bank_postgres
    environment:
      POSTGRES_USER: bankuser
      POSTGRES_PASSWORD: bankpass
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - bank_pgdata:/var/lib/postgresql/data

volumes:
  bank_pgdata:
